spring:
  profiles:
    active: local # Development is ongoing
  application:
    name: favouriteslist
  sql:
    init:
      mode: always # ensure DB script is constructed to generate table only once
      schema-locations: optional:classpath:schema.sql
      data-locations: optional:classpath:data.sql
jikan:
  api:
    url: "https://api.jikan.moe/v4"