spring:
  profiles:
    active: local # Development is ongoing
  application:
    name: favouriteslist
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: none
              create-target: create.sql
              create-source: metadata
jakarta:
  persistence:
    schema-generation:
      create-source: metadata
      drop-source: metadata
jikan:
  api:
    url: "https://api.jikan.moe/v4"